kind: pipeline
type: docker
name: default

steps:
- name: linter
  image: python:buster
  commands:
    - pip3 install salt-lint
    - find . -type f | grep '.sls' | while read file;do salt-lint $file -v;done

trigger:
  branch:
  - master
